#!/usr/bin/env bash
# label-inbox-devin-review.sh — Add devin:review to all Inbox issues that don't have it.
#
# Usage:
#   GH_PAT=<token> ./scripts/label-inbox-devin-review.sh
#
# Requires: gh CLI, jq
# Reads field IDs from .env.project (generated by setup-project.sh).

set -euo pipefail

REPO="sidsaw/ghostfolio"

# ---------------------------------------------------------------------------
# Load env
# ---------------------------------------------------------------------------
ENV_FILE="${ENV_FILE:-.env.project}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: ${ENV_FILE} not found. Run scripts/setup-project.sh first." >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$ENV_FILE"

TOKEN="${GH_PAT:-}"
if [[ -z "$TOKEN" ]]; then
  echo "ERROR: GH_PAT is not set" >&2
  exit 1
fi

for var in PROJECT_ID STATUS_FIELD_ID OPT_INBOX; do
  if [[ -z "${!var:-}" ]]; then
    echo "ERROR: ${var} missing from ${ENV_FILE}. Re-run setup-project.sh." >&2
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# Ensure the devin:review label exists on the repo
# ---------------------------------------------------------------------------
echo "==> Ensuring devin:review label exists on ${REPO}..."
gh label create "devin:review" \
  --repo "$REPO" \
  --color "0075ca" \
  --description "Trigger: ask Devin to review this issue" \
  --force 2>/dev/null || true

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
gql() {
  gh api graphql \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "X-Github-Next-Global-ID: 1" \
    "$@"
}

# ---------------------------------------------------------------------------
# Fetch all project items, paginated
# ---------------------------------------------------------------------------
echo "==> Fetching project items from project ${PROJECT_ID}..."

fetch_page() {
  local cursor_arg="$1"
  gql -f query='
{
  node(id: "'"${PROJECT_ID}"'") {
    ... on ProjectV2 {
      items(first: 100 '"${cursor_arg}"') {
        pageInfo { hasNextPage endCursor }
        nodes {
          id
          fieldValues(first: 20) {
            nodes {
              ... on ProjectV2ItemFieldSingleSelectValue {
                field { ... on ProjectV2SingleSelectField { id } }
                optionId
              }
            }
          }
          content {
            ... on Issue {
              number
              title
              labels(first: 20) {
                nodes { name }
              }
            }
          }
        }
      }
    }
  }
}'
}

ALL_ITEMS='[]'
CURSOR_ARG=""
PAGE=0

while true; do
  PAGE=$((PAGE + 1))
  echo "    Fetching page ${PAGE}..."
  RESP=$(fetch_page "$CURSOR_ARG")

  PAGE_ITEMS=$(echo "$RESP" | jq '.data.node.items.nodes')
  ALL_ITEMS=$(jq -n --argjson a "$ALL_ITEMS" --argjson b "$PAGE_ITEMS" '$a + $b')

  HAS_NEXT=$(echo "$RESP" | jq -r '.data.node.items.pageInfo.hasNextPage')
  END_CURSOR=$(echo "$RESP" | jq -r '.data.node.items.pageInfo.endCursor')

  if [[ "$HAS_NEXT" != "true" ]]; then
    break
  fi
  CURSOR_ARG="after: \"${END_CURSOR}\""
done

TOTAL=$(echo "$ALL_ITEMS" | jq 'length')
echo "    Total items on board: ${TOTAL}"

# ---------------------------------------------------------------------------
# Filter: items with Status == Inbox AND no devin:review label AND are Issues
# ---------------------------------------------------------------------------
TARGETS=$(echo "$ALL_ITEMS" | jq -c \
  --arg fid "$STATUS_FIELD_ID" \
  --arg inbox "$OPT_INBOX" '
  [.[] | select(
    # must be an Issue (has a number field)
    .content.number != null
    # Status field must be Inbox
    and (.fieldValues.nodes | map(select(.field.id == $fid and .optionId == $inbox)) | length) > 0
    # must NOT already have devin:review
    and (.content.labels.nodes | map(.name) | contains(["devin:review"]) | not)
  )]')

TARGET_COUNT=$(echo "$TARGETS" | jq 'length')
echo "==> Inbox issues without devin:review: ${TARGET_COUNT}"

if [[ "$TARGET_COUNT" -eq 0 ]]; then
  echo "Nothing to do — all Inbox issues already have devin:review (or there are no Inbox issues)."
  exit 0
fi

# ---------------------------------------------------------------------------
# Add devin:review label to each target issue
# ---------------------------------------------------------------------------
echo "==> Labeling ${TARGET_COUNT} issue(s)..."

LABELED=0
FAILED=0

while IFS= read -r ITEM; do
  NUMBER=$(echo "$ITEM" | jq -r '.content.number')
  TITLE=$(echo "$ITEM"  | jq -r '.content.title // "(no title)"')

  echo "  → #${NUMBER}: ${TITLE}"

  if gh issue edit "$NUMBER" \
       --repo "$REPO" \
       --add-label "devin:review" \
       --silent 2>/dev/null; then
    echo "    ✓ Added devin:review"
    LABELED=$((LABELED + 1))
  else
    echo "    ✗ Failed to label #${NUMBER}" >&2
    FAILED=$((FAILED + 1))
  fi
done < <(echo "$TARGETS" | jq -c '.[]')

echo ""
echo "============================================================"
echo "  Labeled        : ${LABELED}"
echo "  Failed         : ${FAILED}"
echo "============================================================"

if [[ "$FAILED" -gt 0 ]]; then
  exit 1
fi
