#!/usr/bin/env bash
# seed-inbox.sh — One-time script: move all "No Status" project items to Inbox.
#
# Usage:
#   GH_PAT=<token> ./scripts/seed-inbox.sh
#
# Requires: gh CLI, jq
# Reads field IDs from .env.project (generated by setup-project.sh).

set -euo pipefail

# ---------------------------------------------------------------------------
# Load env
# ---------------------------------------------------------------------------
ENV_FILE="${ENV_FILE:-.env.project}"
if [[ ! -f "$ENV_FILE" ]]; then
  echo "ERROR: ${ENV_FILE} not found. Run scripts/setup-project.sh first." >&2
  exit 1
fi
# shellcheck source=/dev/null
source "$ENV_FILE"

TOKEN="${GH_PAT:-}"
if [[ -z "$TOKEN" ]]; then
  echo "ERROR: GH_PAT is not set" >&2
  exit 1
fi

for var in PROJECT_ID STATUS_FIELD_ID OPT_INBOX; do
  if [[ -z "${!var:-}" ]]; then
    echo "ERROR: ${var} missing from ${ENV_FILE}. Re-run setup-project.sh." >&2
    exit 1
  fi
done

# ---------------------------------------------------------------------------
# Helper
# ---------------------------------------------------------------------------
gql() {
  gh api graphql \
    -H "Authorization: Bearer ${TOKEN}" \
    -H "X-Github-Next-Global-ID: 1" \
    "$@"
}

# ---------------------------------------------------------------------------
# Fetch all project items with their current Status field value.
# Handles pagination up to 500 items (5 pages × 100).
# ---------------------------------------------------------------------------
echo "==> Fetching project items from project ${PROJECT_ID}..."

fetch_page() {
  local cursor_arg="$1"
  gql -f query='
{
  node(id: "'"${PROJECT_ID}"'") {
    ... on ProjectV2 {
      items(first: 100 '"${cursor_arg}"') {
        pageInfo { hasNextPage endCursor }
        nodes {
          id
          fieldValues(first: 20) {
            nodes {
              ... on ProjectV2ItemFieldSingleSelectValue {
                field { ... on ProjectV2SingleSelectField { id } }
                optionId
              }
            }
          }
          content {
            ... on Issue       { title number }
            ... on PullRequest { title number }
            ... on DraftIssue  { title }
          }
        }
      }
    }
  }
}'
}

ALL_ITEMS='[]'
CURSOR_ARG=""
PAGE=0

while true; do
  PAGE=$((PAGE + 1))
  echo "    Fetching page ${PAGE}..."
  RESP=$(fetch_page "$CURSOR_ARG")

  PAGE_ITEMS=$(echo "$RESP" | jq '.data.node.items.nodes')
  ALL_ITEMS=$(jq -n --argjson a "$ALL_ITEMS" --argjson b "$PAGE_ITEMS" '$a + $b')

  HAS_NEXT=$(echo "$RESP" | jq -r '.data.node.items.pageInfo.hasNextPage')
  END_CURSOR=$(echo "$RESP" | jq -r '.data.node.items.pageInfo.endCursor')

  if [[ "$HAS_NEXT" != "true" ]]; then
    break
  fi
  CURSOR_ARG="after: \"${END_CURSOR}\""
done

TOTAL=$(echo "$ALL_ITEMS" | jq 'length')
echo "    Total items on board: ${TOTAL}"

# ---------------------------------------------------------------------------
# Find items with no Status set (Status field absent from fieldValues).
# ---------------------------------------------------------------------------
NO_STATUS_ITEMS=$(echo "$ALL_ITEMS" | jq -c \
  --arg fid "$STATUS_FIELD_ID" '
  [.[] | select(
    (.fieldValues.nodes | map(select(.field.id == $fid)) | length) == 0
  )]')

NO_STATUS_COUNT=$(echo "$NO_STATUS_ITEMS" | jq 'length')
echo "==> Items with no Status: ${NO_STATUS_COUNT}"

if [[ "$NO_STATUS_COUNT" -eq 0 ]]; then
  echo "Nothing to do — all items already have a Status."
  exit 0
fi

# ---------------------------------------------------------------------------
# Move each no-status item to Inbox.
# ---------------------------------------------------------------------------
echo "==> Moving ${NO_STATUS_COUNT} item(s) to Inbox..."

MOVED=0
FAILED=0

while IFS= read -r ITEM; do
  ITEM_ID=$(echo "$ITEM" | jq -r '.id')
  TITLE=$(echo "$ITEM"  | jq -r '.content.title // "(no title)"')
  NUMBER=$(echo "$ITEM" | jq -r '.content.number // ""')
  LABEL="${TITLE}"
  [[ -n "$NUMBER" ]] && LABEL="${TITLE} (#${NUMBER})"

  echo "  → ${LABEL}"

  UPDATE_RESP=$(gql -f query='
mutation {
  updateProjectV2ItemFieldValue(input: {
    projectId: "'"${PROJECT_ID}"'"
    itemId:    "'"${ITEM_ID}"'"
    fieldId:   "'"${STATUS_FIELD_ID}"'"
    value:     { singleSelectOptionId: "'"${OPT_INBOX}"'" }
  }) {
    projectV2Item { id }
  }
}' 2>&1) || true

  UPDATED_ID=$(echo "$UPDATE_RESP" | jq -r '.data.updateProjectV2ItemFieldValue.projectV2Item.id' 2>/dev/null || echo "")
  if [[ -n "$UPDATED_ID" && "$UPDATED_ID" != "null" ]]; then
    echo "    ✓ Moved to Inbox"
    MOVED=$((MOVED + 1))
  else
    echo "    ✗ Failed — response:" >&2
    echo "$UPDATE_RESP" | jq . >&2 2>/dev/null || echo "$UPDATE_RESP" >&2
    FAILED=$((FAILED + 1))
  fi
done < <(echo "$NO_STATUS_ITEMS" | jq -c '.[]')

echo ""
echo "============================================================"
echo "  Moved to Inbox : ${MOVED}"
echo "  Failed         : ${FAILED}"
echo "============================================================"

if [[ "$FAILED" -gt 0 ]]; then
  exit 1
fi
